# Generated by Django 5.2.4 on 2025-09-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название объекта')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('max_guests', models.PositiveIntegerField(verbose_name='Максимальное количетво гостей')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=18, verbose_name='Номер телефона')),
                ('startdate', models.DateField(verbose_name='Дата заселения')),
                ('enddate', models.DateField(verbose_name='Дата выезда')),
                ('guests_amount', models.PositiveIntegerField(verbose_name='Количество гостей')),
                ('comment', models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Комментарий')),
                ('order_cost', models.PositiveIntegerField(verbose_name='Стоимость заказа')),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='Статус аренды')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='main.rentobject', verbose_name='Название объекта')),
            ],
        ),
    ]
