# Generated by Django 5.2.4 on 2025-09-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobject',
            name='img1',
            field=models.ImageField(blank=True, upload_to='houses'),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='img2',
            field=models.ImageField(blank=True, upload_to='houses'),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='img3',
            field=models.ImageField(blank=True, upload_to='houses'),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='img4',
            field=models.ImageField(blank=True, upload_to='houses'),
        ),
        migrations.AlterField(
            model_name='rentobject',
            name='max_guests',
            field=models.PositiveIntegerField(verbose_name='Максимальное количеcтво гостей'),
        ),
    ]
