# Generated by Django 5.2.4 on 2025-09-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rentobject_img1_rentobject_img2_rentobject_img3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentobject',
            options={'verbose_name': 'Объект аренды', 'verbose_name_plural': 'Объекты аренды'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
    ]
