# Generated by Django 5.2.4 on 2025-12-02 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_rentobject_options_alter_timetable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.CreateModel(
            name='DateObjectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datecost', to='main.rentobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Стоимость объекта на определенную дату',
                'verbose_name_plural': 'Стоимости объектов на определенную дату',
            },
        ),
    ]
