# Generated by Django 5.2.4 on 2026-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_timetable_children_pet_rentobject_extra_guest_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobject',
            name='extra_pet_fee',
            field=models.PositiveIntegerField(default=0, help_text='Добавляется к стоимости брони за каждого питомца', verbose_name='Дополнительная плата за питомца'),
        ),
    ]
