# Generated by Django 5.2.4 on 2026-06-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_feedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
    ]
